# Generated by Django 4.1.5 on 2023-01-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserImage',
            new_name='UserProfileImage',
        ),
    ]
